# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160321120913 on 2016-03-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('bodytext', models.TextField(blank=True, max_length=200)),
                ('publication_date', models.DateTimeField(db_index=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
