# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160321120913 on 2016-03-24 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160321_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='bodytext',
            field=models.TextField(blank=True),
        ),
    ]
