# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160321120913 on 2016-03-24 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160324_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_small',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
